### ISSUE TITLE
01-08-2024 New plan for ICMS-OFW Online reporting

### ISSUE THREAD

**Issue by lightdcreator** [koykoy027/icms-ofw-online-reporting#1]
## ICMS - OFW and OSAEC ENHANCEMENT FOR ONLINE REPORTING

   - [x] add another database for online reporting
   - [x] set the URL domain name as online.icms-ofw.com
   - [ ] online reporting must have added new online report and report list in the navbar.
   - [ ] users can check and review his own reports  
   - [ ] add guest registration
   - [ ] #2

**Comment by koykoy027** [comment]
I will close this issue because it will not be needed
